### ISSUE TITLE
The song is being received but no showing in-game

### ISSUE THREAD

**Issue by iam4pple** [mmccall0813/letemknow#2]
In the console it's logged that LetEmKnow is receiving song updates but when checking in game there is no song title. Is there some sort of dependency that's needed or just the mod not working for some reason. I also wouldn't be surprised if it's a side effect of wine. Cider RPC also doesn't work
![image](https://github.com/user-attachments/assets/8043cc07-bcc5-4cf2-90f3-a37dc396ff69)

**Comment by mmccall0813** [comment]
It could potentially be a conflict with another mod, could you send your mods list?

It also could be that you're in a solo session, which the mod doesn't work in due to the way it does networking.

**Comment by iam4pple** [comment]
It was because I was playing offline. Should've thought of that. Anyways, thanks for your help
